/**
 * before_agent_start hook
 *
 * 在 agent 真正开始处理用户输入前，向 system message 注入：
 *   1. profile identity 节选（≤300 字）
 *   2. top entities（窗口 30 天，取前 10）
 *   3. 最近 5 条 long-term 记忆的标题/摘要
 *
 * 返回 `{ additionalContext: <markdown> }`，OpenClaw 会把它拼到 system
 * prompt 末尾。失败时静默返回 {}（"宁可少注入，也别炸 agent"）。
 *
 * 注意：所有调用都是只读，不需要 allowConversationAccess。
 */

const MAX_IDENTITY_CHARS = 300;
const MAX_TOP_ENTITIES = 10;
const MAX_RECENT_MEMORIES = 5;

export function buildBeforeAgentStartHook({ client, logger, now = () => new Date() } = {}) {
  if (!client) throw new Error("before_agent_start: client is required");

  return async function before_agent_start(_event = {}) {
    try {
      const [identity, entities, recent] = await Promise.all([
        client.profile.identity({ max_chars: MAX_IDENTITY_CHARS }).catch(() => ({ ok: false })),
        client.kg.entities({ top: MAX_TOP_ENTITIES, window_days: 30 }).catch(() => ({ ok: false })),
        client.recent({ limit: MAX_RECENT_MEMORIES, type: "long-term" }).catch(() => ({ ok: false })),
      ]);

      const sections = [];
      sections.push(`## 与 abble 的最近上下文`);
      sections.push(`<!-- generated by memoryd openclaw plugin @ ${now().toISOString()} -->`);

      if (identity.ok && identity.data) {
        sections.push(``);
        sections.push(`### Identity 节选`);
        sections.push(truncate(String(identity.data).trim(), MAX_IDENTITY_CHARS));
      }

      if (entities.ok && Array.isArray(entities.data) && entities.data.length > 0) {
        sections.push(``);
        sections.push(`### 最近 30 天 top 实体`);
        for (const e of entities.data.slice(0, MAX_TOP_ENTITIES)) {
          const name = e.name || e.slug || e.id || "(unnamed)";
          const score = typeof e.score === "number" ? ` (score=${e.score.toFixed(2)})` : "";
          const summary = e.summary || e.excerpt || "";
          sections.push(`- ${name}${score}${summary ? ` —— ${summary}` : ""}`);
        }
      }

      if (recent.ok && Array.isArray(recent.data) && recent.data.length > 0) {
        sections.push(``);
        sections.push(`### 最近 ${MAX_RECENT_MEMORIES} 条 long-term 记忆`);
        for (const r of recent.data.slice(0, MAX_RECENT_MEMORIES)) {
          const title = r.title || r.slug || r.memory_id || "(untitled)";
          const created = r.created_at || "";
          sections.push(`- ${title}${created ? ` [${created}]` : ""}`);
        }
      }

      // 至少要有一节有内容才注入；否则保持空，避免污染 system prompt。
      if (sections.length <= 2) {
        return {};
      }

      const additionalContext = sections.join("\n");
      logger?.info?.(`[memoryd] before_agent_start injected ${additionalContext.length} chars`);
      return { additionalContext };
    } catch (e) {
      logger?.warn?.(`[memoryd] before_agent_start failed: ${e?.message || e}`);
      return {};
    }
  };
}

function truncate(s, n) {
  if (!s) return "";
  return s.length > n ? s.slice(0, n) + "..." : s;
}
